[package]
name = "libcubiomes-sys"
version = "0.1.0"
edition = "2021"
authors = [ "EnderKill98 " ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.60.1"
